version: "3.9"
services:
  backend:
    image: team12/airport-backend:dev
    container_name: airport-backend
    ports:
      - "8080:8080"
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: "3307"
      DB_NAME: flight_management
      DB_USER: airport_app
      DB_PASSWORD: "AirportApp2025!"
      SPRING_PROFILES_ACTIVE: local