name: backend-ci
on:
  pull_request:
    paths-ignore: ["**/README.md"]
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven
      - name: Build & Test
        run: ./mvnw -B -DskipITs=true verify